
[project]
name = "nyc-transit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.14"   # pin upper bound so uv doesn't resolve for 3.14+
dependencies = [
    "databricks-sql-connector>=4.2.5",
    "dotenv>=0.9.9",
    "nyct-gtfs>=2.0.0",             # 2.0.0+ = no api_key required
    "polars>=1.39.3",
    "requests>=2.33.0",
]
